apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: gpu-operator
  namespace: kube-amd-gpu
spec:
  driver:
    enable: false
  devicePlugin:
    devicePluginImage: 'rocm/k8s-device-plugin:latest'
    devicePluginImagePullPolicy: IfNotPresent
    nodeLabellerImage: 'rocm/k8s-device-plugin:labeller-latest'
    nodeLabellerImagePullPolicy: IfNotPresent
    enableNodeLabeller: true
  metricsExporter:
    enable: false
  selector:
    feature.node.kubernetes.io/amd-gpu: 'true'
  testRunner:
    enable: true
    logsLocation:
      mountPath: /var/log/amd-test-runner
      hostPath: /var/log/amd-test-runner