apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qwen-coder-1-5b-instruct-backend
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: qwen-coder-1-5b-instruct.default.svc.cluster.local
        port: 8000
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qwen-code-lora
  namespace: envoy-gateway-system
spec:
  endpoints:
    - fqdn:
        hostname: qwen-code-lora.default.svc.cluster.local
        port: 8000